### ISSUE TITLE
发布到npm的包如何引用呢？

### ISSUE THREAD

**Issue by Kellercai** [aisuda/vue-custom-widget-template#4]
- 复现路径：
1、下载本仓库，编译发布到npm
2、项目中下载该组件库，并在入口文件引入
```
import 'multiple-custom-widget-template-test/dist/infoCard.umd'
import 'multiple-custom-widget-template-test/dist/infoCardPlugin.umd'
```
3、进入设计页面，控制台已显示注册成功
![image](https://user-images.githubusercontent.com/20681598/218396652-af4b7c2f-dec3-409a-aaf6-b70a0da0c649.png)
4、但是自定义组件无法找到该组件，页面中引用该type也渲染失败
![image](https://user-images.githubusercontent.com/20681598/218397410-5a2473df-c195-4939-8867-20d5351d8503.png)

- 期望
希望能告知一下，组件库npm包发布上去后，自研项目中如何引用呢？

**Comment by wibetter** [comment]
NPM扩展包主要是在爱速搭平台中使用的，相关使用文档请见：https://baidu.gitee.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/
