### ISSUE TITLE
vue配置面板不生效

### ISSUE THREAD

**Issue by yuuummmii** [aisuda/vue-custom-widget-template#7]
在amis-widget在线demo中，编辑器中修改vue组件的参数，在编辑器中可以看到变化，点击预览之后只能显示默认参数
编辑页面
![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/104764199/2f59570f-ce4e-4acb-9854-a8a257a4b6f7)
预览页面
![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/104764199/c4204800-8bfd-4624-a393-da9382ff60d1)

**Comment by xiaochaochao520** [comment]
解决了嘛

**Comment by xiaochaochao520** [comment]
![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/118751943/b882f57f-52cd-499e-a1fd-bbaec5799e6c)

**Comment by xiaochaochao520** [comment]
@wibetter

**Comment by yuuummmii** [comment]
> 解决了嘛


可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。
https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250

**Comment by xiaochaochao520** [comment]
> > 解决了嘛
> 
> 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
你是换了一个项目嘛

**Comment by yuuummmii** [comment]
> > > 解决了嘛
> > 
> > 
> > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > 你是换了一个项目嘛

没有啊，这个dist文件夹是amis-widget-cli打包生成的

**Comment by xiaochaochao520** [comment]
> > > > 解决了嘛
> > > 
> > > 
> > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > 你是换了一个项目嘛
> 
> 没有啊，这个dist文件夹是amis-widget-cli打包生成的

你就新加了一个这个文件是嘛
![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/118751943/867e333e-d444-41d4-9747-6837671ce7f3)

**Comment by yuuummmii** [comment]
> > > > > 解决了嘛
> > > > 
> > > > 
> > > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > > 你是换了一个项目嘛
> > 
> > 
> > 没有啊，这个dist文件夹是amis-widget-cli打包生成的
> 
> 你就新加了一个这个文件是嘛 ![image](https://user-images.githubusercontent.com/118751943/281246649-867e333e-d444-41d4-9747-6837671ce7f3.png)

这个文件也是生成的，我只是修改了一下里边的方法

**Comment by xiaochaochao520** [comment]
> > > > > > 解决了嘛
> > > > > 
> > > > > 
> > > > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > > > 你是换了一个项目嘛
> > > 
> > > 
> > > 没有啊，这个dist文件夹是amis-widget-cli打包生成的
> > 
> > 
> > 你就新加了一个这个文件是嘛 ![image](https://user-images.githubusercontent.com/118751943/281246649-867e333e-d444-41d4-9747-6837671ce7f3.png)
> 
> 这个文件也是生成的，我只是修改了一下里边的方法

![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/118751943/335f4a6d-e6bc-4c06-aa57-f556ef674b81)
这个东西哪里来的 报这个东西没有

**Comment by xiaochaochao520** [comment]
> > > > > > 解决了嘛
> > > > > 
> > > > > 
> > > > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > > > 你是换了一个项目嘛
> > > 
> > > 
> > > 没有啊，这个dist文件夹是amis-widget-cli打包生成的
> > 
> > 
> > 你就新加了一个这个文件是嘛 ![image](https://user-images.githubusercontent.com/118751943/281246649-867e333e-d444-41d4-9747-6837671ce7f3.png)
> 
> 这个文件也是生成的，我只是修改了一下里边的方法
![image](https://github.com/aisuda/vue2-amis-custom-widget/assets/118751943/acd5742c-8e65-4e28-bd9e-42053cd9d89e)
报这个·错误

**Comment by yuuummmii** [comment]
> > > > > > > 解决了嘛
> > > > > > 
> > > > > > 
> > > > > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > > > > 你是换了一个项目嘛
> > > > 
> > > > 
> > > > 没有啊，这个dist文件夹是amis-widget-cli打包生成的
> > > 
> > > 
> > > 你就新加了一个这个文件是嘛 ![image](https://user-images.githubusercontent.com/118751943/281246649-867e333e-d444-41d4-9747-6837671ce7f3.png)
> > 
> > 
> > 这个文件也是生成的，我只是修改了一下里边的方法
> > ![image](https://user-images.githubusercontent.com/118751943/281250946-acd5742c-8e65-4e28-bd9e-42053cd9d89e.png)
> > 报这个·错误

应该是package.json里边没加这个，安装一下就好了

**Comment by xiaochaochao520** [comment]
> > > > > > > > 解决了嘛
> > > > > > > 
> > > > > > > 
> > > > > > > 可以看一下这个，我修改了componentDidMount和componentDidUpdate方法，目前使用没什么问题。 https://github.com/yuuummmii/amis-editor-vue-custom/blob/003fcc0cc25d3d29ea17b3bba14c9299d5079310/src/amis-editor-plugin/dist/index.esm.js#L250
> > > > > > > 你是换了一个项目嘛
> > > > > 
> > > > > 
> > > > > 没有啊，这个dist文件夹是amis-widget-cli打包生成的
> > > > 
> > > > 
> > > > 你就新加了一个这个文件是嘛 ![image](https://user-images.githubusercontent.com/118751943/281246649-867e333e-d444-41d4-9747-6837671ce7f3.png)
> > > 
> > > 
> > > 这个文件也是生成的，我只是修改了一下里边的方法
> > > ![image](https://user-images.githubusercontent.com/118751943/281250946-acd5742c-8e65-4e28-bd9e-42053cd9d89e.png)
> > > 报这个·错误
> 
> 应该是package.json里边没加这个，安装一下就好了

这种自定义组件配置项里面能配置添加事件的那种吗

**Comment by yuuummmii** [comment]
> 这种自定义组件配置项里面能配置添加事件的那种吗

这个没研究过，可以通过onBuildPanels事件获取到amis组件的配置，对照着写一个试试

**Comment by wibetter** [comment]
可以理解编辑器端切换预览类似一个刷新操作，编辑端的配置面板中的所有配置改动，因为没有保存入库（存入数据库）肯定是会丢失的。所以这不是一个问题。
